name: API Workflow

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "api/**/*"
      - ".github/workflows/api.yaml"
  push:
    branches:
      - "main"
    paths:
      - "api/**/*"
      - ".github/workflows/api.yaml"
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_protected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: api/
          tags: ghcr.io/madetara/yaka/api:0.1.${{ github.run_number }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_image:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_protected }}
    needs: build-and-push-image
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME}}
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: SECRET_KEY_BASE, DB_PASSWORD, DB_NAME, DB_USER, DB_HOST, DB_PORT, GITHUB_TOKEN, GITHUB_RUN_NUMBER
          script: |
            echo $GITHUB_TOKEN | docker login ghcr.io -u madetara --password-stdin
            podman stop yaka-api
            podman rm yaka-api
            podman run -d --name yaka-api --restart unless-stopped -p 3030:3000 \
              -e DB_PASSWORD="$DB_PASSWORD" \
              -e DB_NAME="$DB_NAME" \
              -e DB_USER="$DB_USER" \
              -e DB_HOST="$DB_HOST" \
              -e DB_PORT="$DB_PORT" \
              -e SECRET_KEY_BASE="$SECRET_KEY_BASE" \
              --network yaka-prod \
              "ghcr.io/madetara/yaka/api:0.1.$GITHUB_RUN_NUMBER"
