name: Database deployment

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/database.yaml'
  workflow_dispatch:

jobs:
  deploy_database:
    runs-on: ubuntu-20.04
    env:
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
    steps:
      - name: Deploy via podman
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB
          script: |
            podman stop yaka-db-prod
            podman rm yaka-db-prod
            podman run \
              -d \
              -v /workload/yaka/prod/db:/var/lib/postgresql/data \
              --restart unless-stopped \
              --name yaka-db-prod \
              -p 5432 \
              -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
              -e POSTGRES_USER="$POSTGRES_USER" \
              -e POSTGRES_DB="$POSTGRES_DB" \
              --network yaka-prod \
              postgres:15.1-alpine
